import { useEffect, useState } from 'react';
import { db } from '../lib/firebase';
import { formatDate } from '../lib/utils';
import { doc, getDoc } from 'firebase/firestore';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { 
  ArrowLeft, 
  MapPin, 
  Calendar, 
  User, 
  ShieldAlert, 
  CheckCircle2, 
  AlertTriangle,
  Download,
  Share2,
  ExternalLink,
  Loader2,
  AlertCircle
} from 'lucide-react';
import { motion } from 'motion/react';
import { cn } from '../lib/utils';

interface ReportDetailProps {
  id: string;
  setView: (v: any) => void;
}

export function ReportDetail({ id, setView }: ReportDetailProps) {
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [isExporting, setIsExporting] = useState(false);
  const [selectedFaultIndex, setSelectedFaultIndex] = useState<number | null>(null);

  useEffect(() => {
    async function fetchReport() {
      try {
        const docRef = doc(db, 'inspections', id);
        const snapshot = await getDoc(docRef);
        if (snapshot.exists()) {
          setReport({ id: snapshot.id, ...snapshot.data() });
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    fetchReport();
  }, [id]);

  const generatePDF = async () => {
    if (!report) return;
    setIsExporting(true);
    try {
      const doc = new jsPDF();
      const timestamp = formatDate(report.timestamp?.toDate());

      // Header
      doc.setFillColor(15, 23, 42); // Slate 900
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(245, 158, 11); // Amber 500
      doc.setFontSize(22);
      doc.text('VOLT-EYE AI REPORT', 20, 25);
      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      doc.text(`REPORT_ID: ${report.id}`, 20, 32);

      // Info Section
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
      doc.text('Inspection Metadata', 20, 55);
      doc.setFontSize(10);
      doc.text(`Timestamp: ${timestamp}`, 20, 65);
      doc.text(`Location: ${report.location.lat}, ${report.location.lng}`, 20, 72);
      doc.text(`Inspector: ${report.uploaderEmail}`, 20, 79);

      // Summary
      doc.setFontSize(12);
      doc.text('AI Summary', 20, 95);
      doc.setFontSize(10);
      const splitSummary = doc.splitTextToSize(report.summary || 'No summary available.', 170);
      doc.text(splitSummary, 20, 105);

      // Table
      if (report.faultsDetected?.length > 0) {
        (doc as any).autoTable({
          startY: 130,
          head: [['Fault Type', 'Confidence', 'Severity', 'Description']],
          body: report.faultsDetected.map((f: any) => [
            f.type, 
            `${(f.confidence * 100).toFixed(0)}%`, 
            f.severity?.toUpperCase() || 'N/A',
            f.description
          ]),
          headStyles: { fillColor: [15, 23, 42] },
          styles: { fontSize: 9 }
        });
      } else {
        doc.text('All systems normal. No faults detected.', 20, 140);
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text('Generated by VOLT-EYE AI Grid Intelligence Platform', 105, 285, { align: 'center' });

      doc.save(`VOLTEYE_REPORT_${report.id.slice(0, 8)}.pdf`);
    } catch (error) {
      console.error('PDF Generation Error:', error);
    } finally {
      setIsExporting(false);
    }
  };

  if (loading) {
    return (
      <div className="h-[60vh] flex flex-col items-center justify-center text-slate-500 space-y-3">
        <Loader2 className="animate-spin text-brand-primary" size={32} />
        <span className="font-mono text-xs uppercase tracking-widest">Decrypting analysis...</span>
      </div>
    );
  }

  if (!report) return <div>Report not found.</div>;

  const hasFaults = report.faultsDetected?.length > 0;
  const criticalCount = report.faultsDetected?.filter((f: any) => f.severity === 'critical').length || 0;

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex items-center gap-4">
          <button 
            onClick={() => setView('reports')}
            className="p-3 bg-white/5 border border-white/10 rounded-2xl text-slate-400 hover:text-white hover:bg-white/10 transition-all"
          >
            <ArrowLeft size={20} />
          </button>
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-mono text-brand-primary tracking-widest font-bold uppercase">Report ID: {report.id.slice(0, 12)}</span>
              <span className="text-slate-600">•</span>
              <span className={cn(
                "px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-tighter",
                criticalCount > 0 ? "bg-brand-danger/20 text-brand-danger animate-pulse" : (hasFaults ? "bg-brand-primary/20 text-brand-primary" : "bg-emerald-500/20 text-emerald-400")
              )}>
                {criticalCount > 0 ? 'CRITICAL ALERT' : (hasFaults ? 'Action Required' : 'Inspection Passed')}
              </span>
            </div>
            <h2 className="text-3xl font-bold text-white tracking-tight">Inspection Analysis</h2>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button 
            onClick={generatePDF}
            disabled={isExporting}
            className="flex items-center gap-2 bg-white/5 border border-white/10 px-4 py-2.5 rounded-xl text-sm font-medium hover:bg-white/10 transition-all disabled:opacity-50"
          >
            {isExporting ? <Loader2 className="animate-spin" size={18} /> : <Download size={18} />}
            Generate PDF
          </button>
          <button className="flex items-center gap-2 bg-brand-primary text-slate-900 px-6 py-2.5 rounded-xl text-sm font-bold hover:shadow-[0_0_20px_rgba(245,158,11,0.3)] transition-all uppercase tracking-widest">
            <Share2 size={18} />
            Dispatch
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
        {/* Left: Image & Faults */}
        <div className="xl:col-span-2 space-y-6">
          <div className="glass-panel rounded-3xl overflow-hidden relative group">
            <div className="relative">
              <img 
                src={report.imageUrl} 
                alt="Infrastructure" 
                className="w-full aspect-video object-cover" 
              />
              
              {/* Overlay Bounding Boxes */}
              <div className="absolute inset-0 pointer-events-none">
                {report.faultsDetected?.map((fault: any, index: number) => {
                  const [ymin, xmin, ymax, xmax] = fault.box_2d;
                  const isSelected = selectedFaultIndex === index;
                  
                  return (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className={cn(
                        "absolute border-2 transition-all pointer-events-auto cursor-help shadow-[0_0_15px_rgba(245,158,11,0.2)]",
                        isSelected ? "border-brand-primary bg-brand-primary/10" : 
                        (fault.severity === 'critical' ? "border-brand-danger bg-brand-danger/10" : "border-brand-primary bg-brand-primary/10")
                      )}
                      style={{
                        top: `${ymin / 10}%`,
                        left: `${xmin / 10}%`,
                        width: `${(xmax - xmin) / 10}%`,
                        height: `${(ymax - ymin) / 10}%`,
                      }}
                      onMouseEnter={() => setSelectedFaultIndex(index)}
                      onMouseLeave={() => setSelectedFaultIndex(null)}
                    >
                      <div className={cn(
                        "absolute -top-6 left-0 px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider whitespace-nowrap",
                        isSelected || fault.severity === 'critical' ? "bg-brand-danger text-white" : "bg-brand-primary text-slate-900"
                      )}>
                        {fault.type} ({(fault.confidence * 100).toFixed(0)}%)
                      </div>
                    </motion.div>
                  );
                })}
              </div>

              {/* HUD Overlays */}
              <div className="absolute inset-0 pointer-events-none border-[30px] border-black/20 flex items-center justify-center opacity-40">
                <div className="w-48 h-48 border border-white/20 rounded-full flex items-center justify-center">
                   <div className="w-0.5 h-6 bg-brand-primary/50 absolute top-0"></div>
                   <div className="w-0.5 h-6 bg-brand-primary/50 absolute bottom-0"></div>
                   <div className="h-0.5 w-6 bg-brand-primary/50 absolute left-0"></div>
                   <div className="h-0.5 w-6 bg-brand-primary/50 absolute right-0"></div>
                </div>
              </div>
            </div>
            
            <div className="p-6 bg-[#0D0E12] border-t border-white/5 flex items-center justify-between">
              <div className="flex items-center gap-6">
                <div className="space-y-1">
                  <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">Asset Location</span>
                  <div className="flex items-center gap-1.5 text-slate-200">
                    <MapPin size={14} className="text-brand-primary" />
                    <span className="text-sm font-medium">{report.location.lat.toFixed(6)}, {report.location.lng.toFixed(6)}</span>
                  </div>
                </div>
                <div className="w-px h-8 bg-white/5" />
                <div className="space-y-1">
                  <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">Captured At</span>
                  <div className="flex items-center gap-1.5 text-slate-200">
                    <Calendar size={14} className="text-brand-primary" />
                    <span className="text-sm font-medium">{formatDate(report.timestamp?.toDate())}</span>
                  </div>
                </div>
              </div>
              <a 
                href={`https://www.google.com/maps?q=${report.location.lat},${report.location.lng}`}
                target="_blank"
                className="text-xs text-brand-primary flex items-center gap-1 hover:underline"
              >
                Satellite View
                <ExternalLink size={12} />
              </a>
            </div>
          </div>

          <div className="glass-panel p-6 rounded-3xl space-y-4">
            <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-2">
              <ShieldAlert size={16} className="text-brand-primary" />
              Intelligence Summary
            </h3>
            <p className="text-slate-300 leading-relaxed italic text-sm">
              "{report.summary}"
            </p>
          </div>
        </div>

        {/* Right: Technical Details */}
        <div className="space-y-6">
          <div className="glass-panel p-6 rounded-3xl space-y-6 h-full flex flex-col">
            <div className="flex items-center justify-between border-b border-white/5 pb-4">
              <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-2">
                Detection Log
                <span className="bg-white/5 text-slate-500 font-mono text-[9px] px-2 py-0.5 rounded-full uppercase">
                  {report.faultsDetected?.length || 0} Targets
                </span>
              </h3>
            </div>

            <div className="flex-1 space-y-4 overflow-auto max-h-[600px] pr-2 custom-scrollbar">
              {report.faultsDetected?.map((fault: any, index: number) => (
                <div 
                  key={index}
                  className={cn(
                    "p-4 rounded-xl border transition-all cursor-default",
                    selectedFaultIndex === index 
                      ? "bg-brand-primary/5 border-brand-primary/30 shadow-[0_0_15px_rgba(245,158,11,0.05)]" 
                      : (fault.severity === 'critical' ? "bg-brand-danger/5 border-brand-danger/20" : "bg-[#15171C] border-white/5")
                  )}
                  onMouseEnter={() => setSelectedFaultIndex(index)}
                  onMouseLeave={() => setSelectedFaultIndex(null)}
                >
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                       <span className="font-bold text-white text-xs uppercase">{fault.type}</span>
                       <span className={cn(
                         "text-[8px] font-bold px-1.5 py-0.5 rounded uppercase tracking-widest",
                         fault.severity === 'critical' ? "bg-brand-danger/20 text-brand-danger" : 
                         (fault.severity === 'medium' ? "bg-brand-primary/20 text-brand-primary" : "bg-emerald-500/20 text-emerald-400")
                       )}>
                         {fault.severity || 'N/A'}
                       </span>
                    </div>
                    <span className="text-[9px] font-mono text-slate-500">
                      {(fault.confidence * 100).toFixed(0)}% Match
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-400 leading-normal">{fault.description}</p>
                </div>
              ))}

              {!hasFaults && (
                <div className="flex flex-col items-center justify-center py-20 text-center space-y-4">
                  <div className="w-12 h-12 bg-emerald-500/10 rounded-full flex items-center justify-center">
                    <CheckCircle2 className="text-emerald-400" size={24} />
                  </div>
                  <div>
                    <p className="font-bold text-white text-sm">Clear Scan</p>
                    <p className="text-[10px] text-slate-500 max-w-[150px] mx-auto mt-1 uppercase tracking-wide">Infrastructure integrity verified.</p>
                  </div>
                </div>
              )}
            </div>
            
            <div className="pt-6 border-t border-white/5 space-y-3">
               <div className="flex items-center justify-between text-[9px] font-mono text-slate-600 uppercase tracking-[0.2em]">
                 <span>Uploader</span>
                 <span className="text-slate-400">{report.uploaderEmail}</span>
               </div>
               <div className="flex items-center justify-between text-[9px] font-mono text-slate-600 uppercase tracking-[0.2em]">
                 <span>Status</span>
                 <span className={cn(
                   "font-bold",
                   criticalCount > 0 ? "text-brand-danger" : "text-emerald-500"
                 )}>{criticalCount > 0 ? "ALRT_CRIT" : "V_STABLE"}</span>
               </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
